name: Update Stock Hotspots RSS Feed

on:
  schedule:
    - cron: '0 1 * * *'  # 9:00 CST
    - cron: '0 4 * * *'  # 12:00 CST
    - cron: '0 9 * * *'  # 17:00 CST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests feedgen

      - name: Generate RSS feed
        run: python stock_hotspots_scraper.py

      - name: Debug feed file
        run: |
          echo "Feed size:" $(stat -c "%s" stock_hotspots_feed.xml) "bytes"

      - name: Commit & Push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add stock_hotspots_feed.xml
          git commit -m "Update RSS feed $(date +'%F %T')" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
